name: CI

on:
  push:
    branches:
      - main

  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull images
        run: docker compose pull --ignore-pull-failures || true
      - name: Start services
        run: docker compose up --build -d
      - name: Create test database
        run: |
          docker compose exec php bin/console make:mig
          docker compose exec php bin/console d:m:m 
          docker compose exec php bin/console d:f:l --no-interaction
      - name: Doctrine Schema Validator
        run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
